config/routes.rb
Rails.application.routes.draw do
  resources :cards

  root 'application#index'

  get "/:page" => "static#show"
end

app/models/card.rb
class Card < ActiveRecord::Base

has_attached_file :photo, :storage => :s3, :hash_secret => "longSecretString", :path => ":hash", :bucket => "FlatironPostcard", :styles => { :thumb => "1024x768"}, :default_style => :thumb, :s3_protocol => "https"

validates :photo, :attachment_presence => true


validates_with AttachmentSizeValidator, :attributes => :photo, :less_than => 3.megabytes
validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
validates_presence_of :sender_email, :sender_name, :recipient_name, :recipient_email, :message
validates :sender_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
validates :recipient_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
                                             

def s3_credentials
  { :access_key_id => AWS_ACCESS_KEY_ID, :secret_access_key => AWS_SECRET_ACCESS_KEY}
end

def mail (html_card)
    m = Mandrill::API.new
    message = {  
     :subject=> "Hey, #{self.recipient_name}! #{self.sender_name} sent you a FlatironPostcard!",  
     :from_name=> self.sender_name,
     :text=>"You've received a postcard from FlatironPostcard, but you have HTML emails disabled. Sorry!",  
     :to=>[  
       {  
         :email=> self.recipient_email,  
         :name=> self.recipient_name 
       },
       {  
         :email=> self.sender_email,  
         :name=> self.sender_name 
       } 
     ],  
     :html=>html_card,  
     :from_email=> self.sender_email  
    }  
    sending = m.messages.send message
end
 


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    # @cards = Card.all
    redirect_to new_card_path
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    redirect_to root_url
  end

  # GET /cards/new
  def new
    # binding.pry
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
    redirect_to new_card_path
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        @card.mail (render_to_string('user_mailer/postcard', :layout => false))
        # Tell the UserMailer to send a welcome email after save
        # UserMailer.welcome_email(@card).deliver

        format.html { redirect_to "/thankyou", notice: 'Your card is on its way!' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  # def update
  #   respond_to do |format|
  #     if @card.update(card_params)
  #       format.html { redirect_to new_card_path, notice: 'Card was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @card }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @card.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:sender_email, :recipient_email, :sender_name, :recipient_name, :message, :photo)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def show
    render params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/application/index.html.erb
<center>
  <h3>FlatironPostcard</h3>
  <h4><%= link_to 'Send postcard!', new_card_path %></h4>
  <div id="home">
    <div id="one"><p>Brought to you by</p></div>
    <div id="two"><p>Edward Warren</p></div>
    <div id="three"><p>Koren Leslie Cohen</p></div>
    <div id="four"><p>&amp; Bianca Tompkins</p></div>
   <div id="five"><p>Share the &hearts;</p></div>
   <div id="six"><p>&hearts;</p></div>
  </div>
  <br>
  <br>
  <br>
</center>

app/views/cards/_form.html.erb
<center>
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <br>
    <%= f.text_field :sender_email, placeholder: "Generous Sender Email"%> 
    <%= f.text_field :recipient_email, class: "recipient", placeholder: "Lucky Recipient Email"%> <br><br>
    <%= f.text_field :sender_name, placeholder: "Your Name" %> 
    <%= f.text_field :recipient_name, class: "recipient", placeholder: "Recipient Name" %> 
    <br><br>
    <div class="photo">
      <%= f.file_field :photo, placeholder: "Upload Photo"%>
    </div><br>
    <div class="submit-card">
      <h2>Include a message!</h2>
      <%= f.text_area :message %> <br>
      <%= f.submit "Send postcard!" %>
    </div>
  </div>
<% end %>
</center>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= image_tag "#{card.path}", height: "100"%></td>
        <td><%= card.sender_name %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Card', new_card_path %>
<br><br><br><br><br>

app/views/cards/new.html.erb
<center>
  <h1>FlatironPostcard</h1>
  <%= render 'form' %>
  <br>
  <br>
  <br>
  <br>
</center>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

 <%= image_tag "#{@card.path}", height: "200"%>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/_footer.html.erb
<center>
  <footer>
    <p>&copy; 2014 <%= link_to "FlatironPostcard", root_url %> | <%= link_to "About", "/about" %></p>
    <br>
  </footer>
<center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <%= favicon_link_tag '/favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="keywords" content="postcard, electronic postcard, Flatiron School, web applications, Koren Leslie Cohen, Edward Warren, Bianca Tompkins, Ruby005"/>
  <meta name="description" content="FlatironPostcard is a web application that allows you to send a personalized electronic postcard to family and friends. Share the &hearts;">
  <title>FlatironPostcard - Share the &hearts;!</title>
</head>
<body>
  <div id="container">
    <%= yield %>
    <footer>
      <%= render "layouts/footer" %>
    </footer> 
  </div>
</body>
</html>